# Generated by Django 6.0.2 on 2026-02-20 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recetas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clasificacionreceta',
            name='justificacion',
            field=models.JSONField(blank=True, default=dict, help_text='Dict {restriccion: razon_texto} explicando cada decisión'),
        ),
        migrations.AlterField(
            model_name='clasificacionreceta',
            name='version_prompt',
            field=models.CharField(default='v1', help_text='Versión del prompt usado para reclasificar si cambia', max_length=10),
        ),
        migrations.AlterField(
            model_name='recetamealdb',
            name='area',
            field=models.CharField(blank=True, help_text='Cocina regional (Italian, Mexican, etc.)', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='recetamealdb',
            name='ingredientes_json',
            field=models.JSONField(blank=True, default=list, help_text='Lista de {"ingrediente": "...", "medida": "..."}'),
        ),
        migrations.AlterField(
            model_name='recetamealdb',
            name='nombre_es',
            field=models.CharField(blank=True, help_text='Nombre traducido al español por Gemini', max_length=255, null=True),
        ),
    ]
