# Generated by Django 5.2.8 on 2026-01-26 19:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RestriccionAlimentaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('intolerancias', models.TextField(blank=True, null=True)),
                ('alergias', models.TextField(blank=True, null=True)),
                ('objetivos', models.TextField(blank=True, null=True)),
                ('enfermedades', models.TextField(blank=True, null=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='FormularioNutricionGuardado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sexo', models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Femenino')], max_length=1, null=True)),
                ('edad', models.IntegerField()),
                ('peso', models.FloatField(help_text='Peso actual en kg')),
                ('altura', models.FloatField(help_text='Altura en cm')),
                ('imc', models.FloatField(editable=False, null=True)),
                ('porcentaje_grasa', models.FloatField(editable=False, null=True)),
                ('objetivo', models.CharField(choices=[('Aumentar', 'Aumentar Masa Muscular'), ('Reducir', 'Reducir Grasa Corporal'), ('Mantener', 'Mantener Peso')], max_length=20)),
                ('peso_objetivo', models.FloatField(help_text='Peso deseado en kg')),
                ('plazo_meses', models.IntegerField(help_text='Tiempo para alcanzar el objetivo en meses')),
                ('comidas_preferidas', models.CharField(max_length=200)),
                ('nivel_actividad', models.CharField(choices=[('sedentario', 'Sedentario'), ('ligero', 'Ligero'), ('moderado', 'Moderado'), ('intenso', 'Intenso'), ('muy_intenso', 'Muy intenso')], max_length=20)),
                ('tipo_dieta', models.CharField(choices=[('normal', 'Sin restricciones'), ('vegetariano', 'Vegetariano'), ('vegano', 'Vegano'), ('keto', 'Keto')], max_length=20)),
                ('restricciones_alimentarias', models.TextField(blank=True, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='formularios_nutricion', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Formulario de Nutrición',
                'verbose_name_plural': 'Formularios de Nutrición',
                'ordering': ['-creado_en'],
            },
        ),
        migrations.CreateModel(
            name='DietaGenerada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imc', models.FloatField(blank=True, null=True)),
                ('porcentaje_grasa', models.FloatField(blank=True, null=True)),
                ('tmb', models.FloatField(blank=True, null=True)),
                ('tdee', models.FloatField(blank=True, null=True)),
                ('calorias_diarias', models.IntegerField(blank=True, null=True)),
                ('proteinas_gramos', models.IntegerField(blank=True, null=True)),
                ('grasas_gramos', models.IntegerField(blank=True, null=True)),
                ('carbohidratos_gramos', models.IntegerField(blank=True, null=True)),
                ('contenido_dieta', models.JSONField()),
                ('distribucion_macros_comidas', models.JSONField(blank=True, help_text='Distribución de calorías y macros por cada comida', null=True)),
                ('objetivo', models.CharField(help_text='Objetivo nutricional (definido por el usuario)', max_length=50)),
                ('plazo_meses', models.PositiveIntegerField(help_text='Plazo estimado del objetivo en meses')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dietas_generadas', to=settings.AUTH_USER_MODEL)),
                ('formulario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dieta_generada', to='nutricion.formularionutricionguardado')),
            ],
            options={
                'verbose_name': 'Dieta Generada',
                'verbose_name_plural': 'Dietas Generadas',
                'ordering': ['-creado_en'],
            },
        ),
    ]
