# Generated by Django 6.0.2 on 2026-03-04 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutricion', '0002_remove_tipo_dieta_add_condicion_medica'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formularionutricionguardado',
            name='ingredientes_excluidos',
            field=models.TextField(blank=True, help_text='Lista de ingredientes separados por coma que el usuario no quiere en recetas', null=True),
        ),
    ]
