# Generated by Django 5.2.8 on 2026-02-12 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notificacion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dispositivousuario',
            name='sistema_operativo',
            field=models.CharField(choices=[('Android', 'Android'), ('iOS', 'iOS'), ('Web', 'Web')], default='Web', max_length=20),
        ),
    ]
