# Generated migration copied into project path
from django.db import migrations
# Generated by Django 6.0 on 2025-12-05 13:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('cuerpo', models.TextField()),
                ('imagen_url', models.URLField(blank=True, null=True)),
                ('datos_adicionales', models.JSONField(blank=True, default=dict)),
                ('estado', models.CharField(choices=[('enviada', 'Enviada'), ('entregada', 'Entregada'), ('error', 'Error')], default='enviada', max_length=20)),
                ('respuesta_firebase', models.CharField(blank=True, max_length=500)),
                ('fecha_envio', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones_recibidas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notificación',
                'verbose_name_plural': 'Notificaciones',
                'ordering': ['-fecha_envio'],
            },
        ),
        migrations.CreateModel(
            name='DispositivoUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_fcm', models.CharField(max_length=500, unique=True)),
                ('nombre_dispositivo', models.CharField(blank=True, max_length=100)),
                ('sistema_operativo', models.CharField(choices=[('Android', 'Android'), ('iOS', 'iOS'), ('Web', 'Web')], default='Android', max_length=20)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('ultima_actualizacion', models.DateTimeField(auto_now=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dispositivos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Dispositivo Usuario',
                'verbose_name_plural': 'Dispositivos Usuarios',
                'unique_together': {('usuario', 'token_fcm')},
            },
        ),
    ]
