# Generated by Django 5.2.8 on 2026-02-12 14:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notificacion', '0002_alter_dispositivousuario_sistema_operativo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dispositivousuario',
            options={'ordering': ['-ultima_actualizacion'], 'verbose_name': 'Dispositivo Usuario', 'verbose_name_plural': 'Dispositivos Usuarios'},
        ),
        migrations.AlterField(
            model_name='dispositivousuario',
            name='activo',
            field=models.BooleanField(default=True, help_text='False si el token es reportado como inválido por Firebase'),
        ),
        migrations.AlterField(
            model_name='dispositivousuario',
            name='fecha_registro',
            field=models.DateTimeField(auto_now_add=True, help_text='Primera vez que se registró este token'),
        ),
        migrations.AlterField(
            model_name='dispositivousuario',
            name='nombre_dispositivo',
            field=models.CharField(blank=True, help_text='Ejemplo: Chrome - Windows, Firefox - MacOS', max_length=100),
        ),
        migrations.AlterField(
            model_name='dispositivousuario',
            name='token_fcm',
            field=models.CharField(help_text='Token de Firebase Cloud Messaging', max_length=500),
        ),
        migrations.AlterField(
            model_name='dispositivousuario',
            name='ultima_actualizacion',
            field=models.DateTimeField(auto_now=True, help_text='Última vez que se usó este token'),
        ),
        migrations.AlterField(
            model_name='dispositivousuario',
            name='usuario',
            field=models.ForeignKey(help_text='Usuario dueño de este token', on_delete=django.db.models.deletion.CASCADE, related_name='dispositivos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='notificacion',
            name='datos_adicionales',
            field=models.JSONField(blank=True, default=dict, help_text='Datos extra enviados con la notificación (URLs, IDs, etc.)'),
        ),
        migrations.AlterField(
            model_name='notificacion',
            name='respuesta_firebase',
            field=models.CharField(blank=True, help_text='ID de mensaje de Firebase o mensaje de error', max_length=500),
        ),
        migrations.AddIndex(
            model_name='dispositivousuario',
            index=models.Index(fields=['usuario', 'activo'], name='notif_user_active_idx'),
        ),
        migrations.AddIndex(
            model_name='dispositivousuario',
            index=models.Index(fields=['token_fcm'], name='notif_token_idx'),
        ),
        migrations.AddIndex(
            model_name='dispositivousuario',
            index=models.Index(fields=['activo', 'ultima_actualizacion'], name='notif_active_updated_idx'),
        ),
        migrations.AddIndex(
            model_name='notificacion',
            index=models.Index(fields=['usuario', '-fecha_envio'], name='notif_user_date_idx'),
        ),
        migrations.AddIndex(
            model_name='notificacion',
            index=models.Index(fields=['estado'], name='notif_estado_idx'),
        ),
        migrations.AddIndex(
            model_name='notificacion',
            index=models.Index(fields=['-fecha_envio'], name='notif_date_idx'),
        ),
    ]
