# Generated by Django 5.2.6 on 2026-03-11 18:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendario', '0002_actividad_usuario_notificacion'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='actividad',
            name='usuario',
            field=models.ForeignKey(default=1, help_text='Usuario dueño de esta actividad', on_delete=django.db.models.deletion.CASCADE, related_name='actividades_calendario', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
