# Generated by Django 6.0 on 2025-12-05 01:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicionFisica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(verbose_name='fecha')),
                ('peso', models.FloatField(verbose_name='peso_kg')),
                ('altura', models.FloatField(verbose_name='altura_cm')),
                ('cintura', models.FloatField(blank=True, null=True, verbose_name='cintura_cm')),
                ('cadera', models.FloatField(blank=True, null=True, verbose_name='cadera_cm')),
                ('cuello', models.FloatField(blank=True, null=True, verbose_name='cuello_cm')),
                ('imc', models.FloatField(blank=True, null=True, verbose_name='imc')),
                ('grasa_corporal', models.FloatField(blank=True, null=True, verbose_name='grasa_corporal_pct')),
                ('comentario', models.TextField(blank=True, null=True, verbose_name='comentario')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='usuario')),
            ],
            options={
                'verbose_name': 'Medición Física',
                'verbose_name_plural': 'Mediciones Físicas',
                'ordering': ['-fecha'],
            },
        ),
    ]
