# Generated by Django 5.2.8 on 2026-01-09 16:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seguimiento', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='medicionfisica',
            options={},
        ),
        migrations.RemoveField(
            model_name='medicionfisica',
            name='cadera',
        ),
        migrations.RemoveField(
            model_name='medicionfisica',
            name='cintura',
        ),
        migrations.RemoveField(
            model_name='medicionfisica',
            name='comentario',
        ),
        migrations.RemoveField(
            model_name='medicionfisica',
            name='cuello',
        ),
        migrations.AlterField(
            model_name='medicionfisica',
            name='altura',
            field=models.FloatField(verbose_name='Altura (cm)'),
        ),
        migrations.AlterField(
            model_name='medicionfisica',
            name='fecha',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='medicionfisica',
            name='grasa_corporal',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='medicionfisica',
            name='imc',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='medicionfisica',
            name='peso',
            field=models.FloatField(verbose_name='Peso (kg)'),
        ),
        migrations.AlterField(
            model_name='medicionfisica',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
