# Generated by Django 6.0.2 on 2026-02-19 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seguimiento', '0002_alter_medicionfisica_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='medicionfisica',
            options={'ordering': ['fecha'], 'verbose_name': 'Medición Física', 'verbose_name_plural': 'Mediciones Físicas'},
        ),
    ]
